
server.port: 9100
server.servlet.context-path: /api

BASE_LOCATION: /Users/joe/Documents/java/java_job
DB_NAME: java_job

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_job
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: joe
    password: 271828
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
  web:
    resources:
      static-locations: file:${File.uploadPath}
  mvc:
    static-path-pattern: /staticfiles/**


File:
  uploadPath: ${BASE_LOCATION}/server/upload

mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml


actable:
  table:
    auto: update
  model:
    pack: com.gk.study.entity
  database:
    type: mysql
mybatis-plus:
  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml

wechat:
  appId: wxcfdba2e12f054712
  appSecret: 5fde8b7221c90b8554becafbfe70dafb
  wxApi: https://api.weixin.qq.com/sns/jscode2session